name:                hsaml2
version:             "0.1"
synopsis:            "OASIS Security Assertion Markup Language (SAML) V2.0"
description:         Direct implementation of the SAML XML standard (https://www.oasis-open.org/standards#samlv2.0), along with some related dependencies.  This is currently partial, as the standard is quite extensive, but is sufficient to build a functioning SP and fully validate responses.  The module layout basically follows the standard definition documentation.  Its use still requires a fairly extensive understanding of SAML.
category:            "Security, Network, Web"
license:             Apache-2.0
license-file:        LICENSE
author:              Dylan Simon
maintainer:          "dylan@dylex.net"
copyright:           "2016"

github: dylex/hsaml2

extra-source-files:
  - test/XML/signature-example.xml
  - test/XML/encryption-example.xml

c-sources:
  - SAML2/XML/libxml2_stub.c

dependencies:
  - asn1-encoding
  - asn1-types >= 0.2
  - base >=4.8 && <5
  - base64-bytestring
  - bytestring
  - cryptonite
  - data-default
  - http-types
  - hxt
  - hxt-charproperties
  - hxt-unicode
  - invertible
  - invertible-hxt
  - lens
  - memory
  - mtl
  - network-uri
  - process
  - semigroups
  - silently
  - string-conversions
  - template-haskell
  - time
  - x509
  - zlib

pkg-config-dependencies: libxml-2.0
ghc-options: -Wall

library:
  source-dirs: .

tests:
  spec:
    main: Main.hs
    source-dirs: test
    dependencies:
      - hsaml2
      - HUnit
      - hxt-http
